language: python
python:
    - "3.5"
addons:
    postgresql: "9.4"
env:
    - SQLALCHEMY_DATABASE_URI=postgresql://postgres@localhost:5432/testing
before_script:
    - psql -U postgres -c 'CREATE DATABASE testing;'
    - psql -U postgres -c "CREATE EXTENSION postgis;" testing
cache: pip
install:
    - pip install -r requirements.txt
script: py.test tests