version: '2'

services:
  postgis:
    restart: "always"
    image: "mdillon/postgis:9.6"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    env_file:
      - ./common.env

  cache:
    restart: "always"
    image: "redis"

  message-queue:
    restart: "always"
    image: "redis"

  web:
    restart: "always"
    build: .
    expose:
      - "8000"
    links:
      - postgis:postgis
      - cache:cache
      - message-queue:message-queue
    #command: "gunicorn --log-level debug -w 2 -b :8000 wsgi:app" production
    command: "python /usr/src/app/manage.py runserver -d -r -p 8000 --host=0.0.0.0" # auto reload testing
    volumes:
      - .:/usr/src/app #./local_knowledge:/usr/src/app/local_knowledge
    env_file:
      - ./common.env

  nginx:
    restart: "always"
    image:
      "tutum/nginx"
    volumes:
      - ./docker-data/nginx/sites-enabled-default:/etc/nginx/sites-enabled/default
    ports:
      - "80:80"
    links:
      - "web:web"
