"""Adding osm_id indexes

Revision ID: b4e80eaf05f0
Revises: 3e82cddda66b
Create Date: 2016-10-13 10:39:28.650024

"""

# revision identifiers, used by Alembic.
revision = 'b4e80eaf05f0'
down_revision = '3e82cddda66b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_node_osm_id'), 'node', ['osm_id'], unique=True)
    #op.drop_index('idx_node_geom', table_name='node')
    op.create_index(op.f('ix_way_osm_id'), 'way', ['osm_id'], unique=True)
    #op.drop_index('idx_way_geom', table_name='way')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.create_index('idx_way_geom', 'way', ['geom'], unique=False)
    op.drop_index(op.f('ix_way_osm_id'), table_name='way')
    #op.create_index('idx_node_geom', 'node', ['geom'], unique=False)
    op.drop_index(op.f('ix_node_osm_id'), table_name='node')
    ### end Alembic commands ###
